mysql:
  path: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: MAY
  username: root
  password: root
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  limit-count-ip: 15000
  limit-time-ip: 3600
zap:
  level: info
  format: console
  prefix: '[may]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
