# mysql
mysql:
    path: ''
    port: ''
    config: ''
    db-name: ''
    username: ''
    password: ''
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ''
    log-zap: false
# system
system:
    env: public
    addr: 8080
    db-type: mysql
    router-prefix: '/v1'
    oss-type: local
    use-multipoint: false
    use-redis: false
    limit-count-ip: 15000
    limit-time-ip: 3600
# zap
zap:
    level: info
    format: console
    prefix: '[github.com/shansec/go-vue-admin]'
    director: log
    show-line: true
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    log-in-console: true
# jwt
jwt:
    signing-key: 5adfc23f-2f8d-47d9-a370-36b37493f202
    expires-time: 604800
    buffer-time: 86400
    issuer: 'Shansec'
# captcha
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
# autocode
autocode:
    s-model: /model/%s
    s-router: /router/%s
    s-server: /server
    s-api: /api/v1/%s
    s-plug: /plugin/%s
    s-initialize: /initialize
    root:
    w-root:
    w-table: /views
    w-web: /src
    s-service: /service/%s
    s-request: /model/%s/request/
    w-api: /api
    w-form: /views
    transfer-restart: true
